version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.15.0
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.15.0
    command: filebeat -e -strict.perms=false
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /c/Projects/DiecastFinder2/wanted/target/surefire-reports:/var/log/wanted:ro
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
#      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  elasticsearch-data-volume:
    driver: local

networks:
  elastic: