filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/logs/*.log
      - /var/log/tests/*.txt
output.console:
  pretty: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]